[package]
name = "base62-uuid"
version = "2.1.2"
edition = "2021"
description = "Minimalist crate to generate Base62 UUIDs"
license = "MIT"
repository = "https://github.com/qtfkwk/base62-uuid"

[dependencies]
base62 = "2.2.1"
clap = { version = "4.5.30", features = ["derive"] }
clap-cargo = "0.15.2"
uuid = { version = "1.13.2", features = ["v4"] }
