[package]
name = "base62-uuid"
version = "2.1.1"
edition = "2021"
description = "Minimalist crate to generate Base62 UUIDs"
license = "MIT"
repository = "https://github.com/qtfkwk/base62-uuid"

[dependencies]
base62 = "2.0.3"
clap = { version = "4.5.22", features = ["derive"] }
clap-cargo = "0.14.1"
uuid = { version = "1.11.0", features = ["v4"] }
